#!/usr/bin/env perl
use Mojolicious::Lite;
use Mojo::Util qw/slurp/;
use Encode;

plugin 'Directory' => {
    root       => app->home->rel_dir('resources'),
    auto_index => 0,
    dir_index  => [qw/index.html index.htm/],
    handler    => sub { _handler(@_) },
};

sub _handler {
    my ( $c, $path ) = @_;
    if ( -f $path && $path =~ /\.epl?$/ ) {
        return if ( $c->param('format') && $c->param('format') eq 'raw' );
        my ($format) = $path =~ m|(?:\.([^\.]+))?\.(?:[^\.]+)$|;
        $format ||= 'txt';
        my $ep = decode_utf8(slurp $path); # テンプレートはutf-8であることを期待します
        # handlerを指定すると$selfがMojo::Templateになるので注意
        $c->render( inline => $ep, format => $format );
    }
}

app->start;
